'use client';

import { Loader2, Table2 } from 'lucide-react';

import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { PageHeader } from '@/components/ui/page-header';
import { useExportReport } from '@/features/analytics/use-analytics';

const REPORTS = [
  {
    type: 'outlet-sales',
    title: 'Sales summary',
    description: 'Campaign sales and points generated by your outlet.',
  },
  {
    type: 'outlet-customers',
    title: 'Customer registrations',
    description: 'Customers registered through your outlet.',
  },
];

export default function OutletReportsPage() {
  const exportReport = useExportReport();
  // React Query exposes the in-flight variables, so we can spin the exact
  // report being generated.
  const active = exportReport.isPending ? exportReport.variables : undefined;

  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports"
        description="Export your outlet performance reports."
      />
      <div className="grid gap-4 md:grid-cols-2">
        {REPORTS.map((r) => (
          <Card key={r.type}>
            <CardHeader>
              <CardTitle>{r.title}</CardTitle>
              <CardDescription>{r.description}</CardDescription>
            </CardHeader>
            <CardContent />
            <CardFooter>
              <Button
                variant="outline"
                size="sm"
                disabled={exportReport.isPending}
                aria-busy={active?.type === r.type}
                aria-label={`Download ${r.title} as CSV`}
                onClick={() => exportReport.mutate({ type: r.type })}
              >
                {active?.type === r.type ? (
                  <Loader2 className="h-4 w-4 animate-spin" aria-hidden />
                ) : (
                  <Table2 className="h-4 w-4" aria-hidden />
                )}
                Download CSV
              </Button>
            </CardFooter>
          </Card>
        ))}
      </div>
    </div>
  );
}
