'use client';

import { FileSpreadsheet, FileText, Loader2, Table2 } from 'lucide-react';

import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { PageHeader } from '@/components/ui/page-header';
import { useExportReport } from '@/features/analytics/use-analytics';

const REPORTS = [
  {
    type: 'outlet-sales',
    title: 'Sales summary',
    description: 'Campaign sales and points generated by your outlet.',
  },
  {
    type: 'outlet-customers',
    title: 'Customer registrations',
    description: 'Customers registered through your outlet.',
  },
];

const FORMATS = [
  { format: 'csv' as const, label: 'CSV', icon: Table2 },
  { format: 'excel' as const, label: 'Excel', icon: FileSpreadsheet },
  { format: 'pdf' as const, label: 'PDF', icon: FileText },
];

export default function OutletReportsPage() {
  const exportReport = useExportReport();
  // React Query exposes the in-flight variables, so we can show a spinner on
  // the exact button being generated while disabling the others.
  const active = exportReport.isPending ? exportReport.variables : undefined;

  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports"
        description="Export your outlet performance reports."
      />
      <div className="grid gap-4 md:grid-cols-2">
        {REPORTS.map((r) => (
          <Card key={r.type}>
            <CardHeader>
              <CardTitle>{r.title}</CardTitle>
              <CardDescription>{r.description}</CardDescription>
            </CardHeader>
            <CardContent />
            <CardFooter className="gap-2">
              {FORMATS.map(({ format, label, icon: Icon }) => {
                const isThisLoading =
                  active?.type === r.type && active?.format === format;
                return (
                  <Button
                    key={format}
                    variant="outline"
                    size="sm"
                    disabled={exportReport.isPending}
                    aria-busy={isThisLoading}
                    aria-label={`Export ${r.title} as ${label}`}
                    onClick={() =>
                      exportReport.mutate({ type: r.type, format })
                    }
                  >
                    {isThisLoading ? (
                      <Loader2 className="h-4 w-4 animate-spin" aria-hidden />
                    ) : (
                      <Icon className="h-4 w-4" aria-hidden />
                    )}
                    {label}
                  </Button>
                );
              })}
            </CardFooter>
          </Card>
        ))}
      </div>
    </div>
  );
}
