'use client';

import { FileSpreadsheet, FileText, Table2 } from 'lucide-react';

import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { PageHeader } from '@/components/ui/page-header';
import { useExportReport } from '@/features/analytics/use-analytics';

const REPORTS = [
  {
    type: 'outlet-sales',
    title: 'Sales summary',
    description: 'Campaign sales and points generated by your outlet.',
  },
  {
    type: 'outlet-customers',
    title: 'Customer registrations',
    description: 'Customers registered through your outlet.',
  },
];

export default function OutletReportsPage() {
  const exportReport = useExportReport();

  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports"
        description="Export your outlet performance reports."
      />
      <div className="grid gap-4 md:grid-cols-2">
        {REPORTS.map((r) => (
          <Card key={r.type}>
            <CardHeader>
              <CardTitle>{r.title}</CardTitle>
              <CardDescription>{r.description}</CardDescription>
            </CardHeader>
            <CardContent />
            <CardFooter className="gap-2">
              <Button
                variant="outline"
                size="sm"
                disabled={exportReport.isPending}
                onClick={() =>
                  exportReport.mutate({ type: r.type, format: 'csv' })
                }
              >
                <Table2 className="h-4 w-4" /> CSV
              </Button>
              <Button
                variant="outline"
                size="sm"
                disabled={exportReport.isPending}
                onClick={() =>
                  exportReport.mutate({ type: r.type, format: 'excel' })
                }
              >
                <FileSpreadsheet className="h-4 w-4" /> Excel
              </Button>
              <Button
                variant="outline"
                size="sm"
                disabled={exportReport.isPending}
                onClick={() =>
                  exportReport.mutate({ type: r.type, format: 'pdf' })
                }
              >
                <FileText className="h-4 w-4" /> PDF
              </Button>
            </CardFooter>
          </Card>
        ))}
      </div>
    </div>
  );
}
